name: test_task
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^0.13.1

  provider: ^5.0.0

  shimmer: ^1.1.2

  cached_network_image: ^3.0.0

  sqflite: ^2.0.0+3

  data_connection_checker: ^0.3.4

  webview_flutter: ^2.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
